import { useState } from 'react';
import { Plus, RotateCcw, Layers3, Trash2 } from 'lucide-react';
import Panel from '../common/Panel';
import StatusBadge from '../common/StatusBadge';

export default function SchedulerPage({ simulation }) {
  const [form, setForm] = useState({ name:'', cpu:4, memory:16, duration:2, priority:'Medium', flexible:true, deadline:24, baselineStart:12, cluster:'CPU Cluster' });
  const [bulkRunning, setBulkRunning] = useState(false);
  const [bulkCount, setBulkCount] = useState(0);
  function submit(event) { event.preventDefault(); if (!form.name.trim()) return; simulation.addJob({ ...form, id:`JOB-${String(simulation.rawJobs.length+1).padStart(3,'0')}`, cpu:Number(form.cpu), memory:Number(form.memory), duration:Number(form.duration), deadline:Number(form.deadline), baselineStart:Number(form.baselineStart) }); setForm({...form,name:''}); }
  async function simulateBulk() { setBulkRunning(true); setBulkCount(0); const generated=Array.from({length:100},(_,i)=>({id:`BULK-${String(i+1).padStart(3,'0')}`,name:['Batch ETL','Model training','Backup archive','Analytics query'][i%4],cpu:2+(i%6),memory:8+(i%5)*8,duration:1+(i%4),priority:i%10===0?'High':'Medium',flexible:true,deadline:24+(i%18),baselineStart:i%20,cluster:i%3===0?'GPU Cluster':i%3===1?'CPU Cluster':'High-efficiency Cluster'})); for(let i=0;i<generated.length;i+=5){simulation.addJob(generated.slice(i,i+5)[0]);setBulkCount(i+5);await new Promise(resolve=>setTimeout(resolve,55))} setBulkRunning(false); }
  return <><div className="section-title"><div><h2>Workload scheduler</h2><p>Create workloads, stress-test queue scale, and inspect dispatch state.</p></div><div className="button-row"><button className="secondary" onClick={simulation.resetQueue}><RotateCcw size={15}/> Reset queue</button><button className="secondary" onClick={simulateBulk} disabled={bulkRunning}><Layers3 size={15}/> {bulkRunning?`Injecting ${bulkCount}/100`:'Simulate 100 jobs'}</button></div></div><Panel title="Create flexible workload" tag="QUEUE INPUT"><form className="workload-form" onSubmit={submit}>{[['name','Workload name','text'],['cpu','CPU cores','number'],['memory','Memory GB','number'],['duration','Duration hours','number'],['deadline','Deadline hour','number']].map(([key,label,type])=><label>{label}<input type={type} value={form[key]} onChange={e=>setForm({...form,[key]:e.target.value})}/></label>)}<label>Priority<select value={form.priority} onChange={e=>setForm({...form,priority:e.target.value})}><option>Low</option><option>Medium</option><option>High</option><option>Critical</option></select></label><button className="primary" type="submit"><Plus size={15}/> Add to queue</button></form></Panel><Panel title="Automation workload queue" tag={`${simulation.jobs.length} JOBS`}><table><thead><tr><th>Job</th><th>State</th><th>Priority</th><th>Resources</th><th>Baseline</th><th>AquaCool</th><th>Progress</th><th>Action</th><th/></tr></thead><tbody>{simulation.jobs.map(job=><tr key={job.id}><td><b>{job.id}</b><small>{job.name}</small></td><td><StatusBadge state={job.state}/></td><td>{job.priority}</td><td>{job.cpu} CPU / {job.memory} GB</td><td>{job.baselineStart}:00</td><td>{job.recommendedStartLabel||'—'}</td><td>{job.progress||0}%</td><td>{job.dispatchMessage||job.reason}</td><td><button className="icon-button" onClick={()=>simulation.removeJob(job.id)}><Trash2 size={14}/></button></td></tr>)}</tbody></table></Panel></>}
