import { useMemo, useState } from 'react';
import { INITIAL_JOBS } from '../app/constants';
import { createEnvironment } from '../simulation/environment';
import { runScheduler } from '../simulation/scheduler';
import { createDispatchTimeline } from '../simulation/dispatchSimulator';
export function useSimulation(facility){
 const [jobs,setJobs]=useState(INITIAL_JOBS); const [result,setResult]=useState(null); const [running,setRunning]=useState(false); const [events,setEvents]=useState([]); const [runStep,setRunStep]=useState(0); const environment=useMemo(()=>createEnvironment(facility.profile),[facility.profile]);
 const displayed=result?.jobs||jobs.map(j=>({...j,recommendedStart:j.baselineStart,state:j.flexible?'QUEUED':'LOCKED_CRITICAL',progress:0,finish:j.baselineStart+j.duration,reason:'Run scheduling automation to evaluate this workload.'}));
 async function runAutomation(){if(running)return;setRunning(true);setResult(null);const add=(text,type='active')=>setEvents(e=>[...e,{time:new Date().toLocaleTimeString(),text,type}]);setRunStep(1);add(`Ingested ${jobs.length} workloads`);await pause(500);setRunStep(2);add(`Classified ${jobs.filter(j=>!j.flexible).length} critical and ${jobs.filter(j=>j.flexible).length} flexible jobs`);await pause(550);add(`Locked ${jobs.filter(j=>!j.flexible)[0]?.id||'critical workloads'} for immediate execution`);setRunStep(3);await pause(650);add('Evaluated feasible windows against deadlines, capacity and environmental scores');const scheduled=runScheduler(jobs,environment,facility.capacity);setRunStep(4);scheduled.jobs.filter(j=>j.state==='APPROVED').forEach(j=>add(`Approved ${j.id} for ${j.recommendedStartLabel}`));await pause(600);setRunStep(5);add('Dispatch queue populated');const dispatch=createDispatchTimeline(scheduled.jobs);setResult({...scheduled,jobs:dispatch});await pause(700);setRunStep(6);add('Simulation completed','done');setRunning(false)}
 function addJob(job){setJobs(j=>[...j,job]);setResult(null)} function removeJob(id){setJobs(j=>j.filter(x=>x.id!==id));setResult(null)} return {jobs:displayed,rawJobs:jobs,environment,metrics:result?.metrics||{carbonReduction:0,waterReduction:0,slaCompliance:100,jobsShifted:0,queued:jobs.length,completed:0,blocked:0,dispatching:0,peakCpu:0,latencyMs:0},events,runStep,running,runAutomation,addJob,removeJob}; }
function pause(ms){return new Promise(resolve=>setTimeout(resolve,ms));}
